package com.woniu.mapper;

import com.woniu.entity.Housestatus;
import com.woniu.entity.HousestatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HousestatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    long countByExample(HousestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int deleteByExample(HousestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int deleteByPrimaryKey(Integer housestatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int insert(Housestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int insertSelective(Housestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    List<Housestatus> selectByExample(HousestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    Housestatus selectByPrimaryKey(Integer housestatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Housestatus record, @Param("example") HousestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int updateByExample(@Param("record") Housestatus record, @Param("example") HousestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int updateByPrimaryKeySelective(Housestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table housestatus
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    int updateByPrimaryKey(Housestatus record);
}