package com.woniu.entity;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uname
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.upass
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    private String upass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.isdelete
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.indeptid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    private Integer indeptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uname
     *
     * @return the value of userinfo.uname
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uname
     *
     * @param uname the value for userinfo.uname
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.upass
     *
     * @return the value of userinfo.upass
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.upass
     *
     * @param upass the value for userinfo.upass
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public void setUpass(String upass) {
        this.upass = upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.isdelete
     *
     * @return the value of userinfo.isdelete
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.isdelete
     *
     * @param isdelete the value for userinfo.isdelete
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.indeptid
     *
     * @return the value of userinfo.indeptid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public Integer getIndeptid() {
        return indeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.indeptid
     *
     * @param indeptid the value for userinfo.indeptid
     *
     * @mbg.generated Thu Aug 15 14:42:51 CST 2019
     */
    public void setIndeptid(Integer indeptid) {
        this.indeptid = indeptid;
    }
}